server.port=9000

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000

jwt.secret=cle-secrete-tres-longue-a-changer-en-production-minimum-256-bits
jwt.expiration=86400000

logging.level.org.springframework.security=DEBUG

logging.level.org.springframework.security.oauth2.server.authorization=TRACE



spring.application.name=collaborationtool

logging.level.com.elprofesor=DEBUG

spring.jpa.show-sql=true


spring.jpa.properties.hibernate.format_sql=true


logging.level.org.hibernate.orm.jdbc.bind=trace

